/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 6
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_capture_reference = 1,
  anon_sym_DOLLAR_AMP = 2,
  anon_sym_DOLLAR_BQUOTE = 3,
  anon_sym_DOLLAR_SQUOTE = 4,
  sym_dollar_escape = 5,
  sym_escape_sequence = 6,
  sym_text = 7,
  sym_document = 8,
  sym_match_reference = 9,
  aux_sym_document_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_capture_reference] = "capture_reference",
  [anon_sym_DOLLAR_AMP] = "$&",
  [anon_sym_DOLLAR_BQUOTE] = "$`",
  [anon_sym_DOLLAR_SQUOTE] = "$'",
  [sym_dollar_escape] = "dollar_escape",
  [sym_escape_sequence] = "escape_sequence",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_match_reference] = "match_reference",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_capture_reference] = sym_capture_reference,
  [anon_sym_DOLLAR_AMP] = anon_sym_DOLLAR_AMP,
  [anon_sym_DOLLAR_BQUOTE] = anon_sym_DOLLAR_BQUOTE,
  [anon_sym_DOLLAR_SQUOTE] = anon_sym_DOLLAR_SQUOTE,
  [sym_dollar_escape] = sym_dollar_escape,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_match_reference] = sym_match_reference,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_capture_reference] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_dollar_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_match_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '$') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 1:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_capture_reference);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_capture_reference);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DOLLAR_AMP);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_DOLLAR_BQUOTE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOLLAR_SQUOTE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_dollar_escape);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '$') ADVANCE(8);
      if (lookahead == '&') ADVANCE(5);
      if (lookahead == '\'') ADVANCE(7);
      if (lookahead == '0') ADVANCE(1);
      if (lookahead == '`') ADVANCE(6);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$') ADVANCE(9);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '\\') ADVANCE(12);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_capture_reference] = ACTIONS(1),
    [anon_sym_DOLLAR_AMP] = ACTIONS(1),
    [anon_sym_DOLLAR_BQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR_SQUOTE] = ACTIONS(1),
    [sym_dollar_escape] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(5),
    [sym_match_reference] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_capture_reference] = ACTIONS(5),
    [anon_sym_DOLLAR_AMP] = ACTIONS(7),
    [anon_sym_DOLLAR_BQUOTE] = ACTIONS(7),
    [anon_sym_DOLLAR_SQUOTE] = ACTIONS(7),
    [sym_dollar_escape] = ACTIONS(5),
    [sym_escape_sequence] = ACTIONS(5),
    [sym_text] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_match_reference] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_capture_reference] = ACTIONS(13),
    [anon_sym_DOLLAR_AMP] = ACTIONS(7),
    [anon_sym_DOLLAR_BQUOTE] = ACTIONS(7),
    [anon_sym_DOLLAR_SQUOTE] = ACTIONS(7),
    [sym_dollar_escape] = ACTIONS(13),
    [sym_escape_sequence] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym_match_reference] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_capture_reference] = ACTIONS(19),
    [anon_sym_DOLLAR_AMP] = ACTIONS(22),
    [anon_sym_DOLLAR_BQUOTE] = ACTIONS(22),
    [anon_sym_DOLLAR_SQUOTE] = ACTIONS(22),
    [sym_dollar_escape] = ACTIONS(19),
    [sym_escape_sequence] = ACTIONS(19),
    [sym_text] = ACTIONS(25),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(28),
    [sym_capture_reference] = ACTIONS(28),
    [anon_sym_DOLLAR_AMP] = ACTIONS(28),
    [anon_sym_DOLLAR_BQUOTE] = ACTIONS(28),
    [anon_sym_DOLLAR_SQUOTE] = ACTIONS(28),
    [sym_dollar_escape] = ACTIONS(28),
    [sym_escape_sequence] = ACTIONS(28),
    [sym_text] = ACTIONS(30),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_match_reference, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_match_reference, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_regex_replacement(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "regex_replacement",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
